### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by johnleoclaudio** [kylereblora/cointrack#1]
When the extension is clicked, it takes a while for the prices to show. 

One solution could be to utilize caching. Only change the state/ update the prices if there's a new data available already.

**Comment by kylereblora** [comment]
Currently, I'm using the `useSWR` hook for fetching and caching the data automatically. On initial page load, it does need a short amount of time to fetch the up-to-date data (as with any other app that loads initially), but `useSWR` caches the response automatically after. It's also pretty cool how the data is cached for a few seconds even after you close the extension. Additionally, it also handles the interval for how often the data is refreshed (`refreshInterval`). 

Caching is pretty much handled in the app, and it's normal for the initial page load to take a short amount of time to display the updated data. I also wouldn't want to handle the caching manually (e.g. storing and retrieving the data somewhere else like `localStorage`) since the problem of re/validating the cache is beyond my understanding 😅.

**Comment by johnleoclaudio** [comment]
Sounds good. Nice app 😁  💯
